# Generated by Django 4.2.1 on 2023-05-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyper_keeper', '0002_clothes_edibles_homeappliances_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='edibles',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='edibles',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='edibles',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='edibles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='homeappliances',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='homeappliances',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='homeappliances',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='homeappliances',
            name='price',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothe_type',
            field=models.CharField(max_length=30, verbose_name='clothe type'),
        ),
        migrations.CreateModel(
            name='HomeAppliancesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='model')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('price', models.PositiveBigIntegerField(default=10000, verbose_name='price')),
                ('discount', models.CharField(blank=True, max_length=10, verbose_name='discount')),
                ('homeApplianceImage', models.ImageField(upload_to='homeAppliances/', verbose_name='home appliance image')),
                ('Description', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('homeAppliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyper_keeper.homeappliances')),
            ],
            options={
                'verbose_name': 'home appliance model',
                'verbose_name_plural': 'home appliances model',
                'db_table': 'home_appliances_model',
            },
        ),
        migrations.CreateModel(
            name='EdiblesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, verbose_name='mark')),
                ('taste', models.CharField(blank=True, max_length=30, verbose_name='taste')),
                ('price', models.PositiveBigIntegerField(default=1000, verbose_name='price')),
                ('discount', models.CharField(blank=True, max_length=10, verbose_name='discount')),
                ('edibleImage', models.ImageField(blank=True, null=True, upload_to='edibles/', verbose_name='edible image')),
                ('Description', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('edible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyper_keeper.edibles', verbose_name='edible')),
            ],
            options={
                'verbose_name': 'edible model',
                'verbose_name_plural': 'edibles model',
                'db_table': 'edibles_models',
            },
        ),
        migrations.CreateModel(
            name='ClothesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='color')),
                ('count', models.IntegerField(blank=True, verbose_name='count')),
                ('price', models.PositiveBigIntegerField(blank=True, default=100000, verbose_name='price')),
                ('discount', models.CharField(blank=True, max_length=10, verbose_name='discount')),
                ('category_image', models.ImageField(upload_to='cothes/', verbose_name='clothe image')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('uodatedTime', models.DateTimeField(auto_now_add=True)),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyper_keeper.clothes', verbose_name='clothe model')),
            ],
            options={
                'verbose_name': 'clothe model',
                'verbose_name_plural': 'clothes model',
                'db_table': 'clothe_model',
            },
        ),
    ]
